#!/usr/bin/env python3
"""Generate tests/support/scan_capture_fixture.hpp from a pakon-captures JSONL.

The capture corpus (github.com/alibosworth/pakon-captures) records image
pixels omitted, so the fixture carries the command channel only: every
non-poll cmd/rsp exchange of one session, in order, verbatim hex, plus the
EP6 image-window shape (chunk size and byte totals per window) that the
captures DO record.

Usage:
    python3 tools/gen_scan_fixture.py <capture.jsonl> <out.hpp>

Provenance comments (source repo commit, file name, session label) are
emitted into the header so the fixture stays traceable.
"""

import json
import subprocess
import sys

# Status polls the OEM issues in a tight loop; they are collapsed out of the
# fixture (the runner only polls the light service register — see
# src/pakon/scan/plan.cpp). READ_STATUS frames (type 03) to HOST/PICL/PICM
# and the READ reg 0x02 service polls are all part of that loop. The one
# service poll whose reply payload is non-zero (service wanted) is kept as a
# named constant instead.
POLL_REQS = {"030110", "030140", "030144", "0103400102", "0103440102"}
SERVICE_POLL_REQS = {"0103400102", "0103440102"}


def extract(path):
    exchanges = []
    service_polls = []
    windows = []
    pending = None
    chunk_sizes = set()
    with open(path) as f:
        for line in f:
            j = json.loads(line)
            d = j.get("d")
            if d == "cmd":
                pending = (j["t"], j["hex"])
            elif d == "rsp" and pending is not None:
                t, req = pending
                rsp = j["hex"]
                pending = None
                if req in POLL_REQS:
                    # READ reg 0x02 replies are 01 <n> <addr> <flags> <val>;
                    # the payload value 02 means "wants service". HOST polls
                    # (03 01 10 -> 03 03 10 <st> aa) never carry it.
                    if req in SERVICE_POLL_REQS and rsp[-2:] != "00":
                        service_polls.append((t, req, rsp))
                else:
                    exchanges.append((t, req, rsp))
            elif d == "ep6":
                windows.append((j["t"], j["n"]))
                chunk_sizes.add(j["n"])
    return exchanges, service_polls, windows, chunk_sizes


def split_windows(windows, gap=0.05):
    """Split the ep6 byte-count events into windows at gaps > gap seconds."""
    if not windows:
        return []
    out = []
    start = 0
    for i in range(len(windows) - 1):
        if windows[i + 1][0] - windows[i][0] > gap:
            out.append(windows[start:i + 1])
            start = i + 1
    out.append(windows[start:])
    return out


def repo_commit(repo_dir):
    try:
        return subprocess.run(
            ["git", "-C", repo_dir, "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def main():
    if len(sys.argv) != 3:
        sys.stderr.write(__doc__)
        return 2
    src, out = sys.argv[1], sys.argv[2]
    exchanges, service_polls, events, chunk_sizes = extract(src)
    wins = split_windows(events)
    commit = repo_commit(src.split("/captures/")[0]) if "/captures/" in src else "unknown"
    label = src.rsplit("/", 2)[-2] + "/" + src.rsplit("/", 1)[-1]

    lines = []
    a = lines.append
    a("#pragma once")
    a("")
    a("// GENERATED FILE — do not edit by hand.")
    a("//")
    a("// Generated by tools/gen_scan_fixture.py from the pakon-captures")
    a("// corpus (github.com/alibosworth/pakon-captures, repo commit")
    a("// %s):" % commit)
    a("//   %s" % label)
    a("//")
    a("// Contents: every non-poll cmd/rsp exchange of the session in wire")
    a("// order, verbatim hex [capture evidence], the service-wanted poll")
    a("// reply (the only poll reply in this session whose payload is not")
    a("// 00), and the EP6 image-window shape. Image pixels are NOT part of")
    a("// the capture corpus (FORMAT.md: 'image-data transfer, byte count")
    a("// only, pixels omitted'), so row data for tests is synthetic.")
    a("")
    a("namespace pakon::test::scan_fixture {")
    a("")
    a("struct Exchange {")
    a("    const char* req;   // request frame, hex")
    a("    const char* rsp;   // recorded reply, hex")
    a("    double t;          // seconds since the first command")
    a("};")
    a("")
    t0 = exchanges[0][0]
    a("// Non-poll exchanges in recorded order (%d frames)." % len(exchanges))
    a("inline constexpr Exchange kSession[] = {")
    for t, req, rsp in exchanges:
        a('    {"%s", "%s", %.3f},' % (req, rsp, t - t0))
    a("};")
    a("")
    if service_polls:
        t, req, rsp = service_polls[0]
        a("// The service-wanted poll of this session (READ PICL reg 0x02:")
        a("// reply flags 0x88 = event pending, payload 02 = wants service).")
        a('inline constexpr const char* kServicePollReq = "%s";' % req)
        a('inline constexpr const char* kServicePollRsp = "%s";' % rsp)
        a("")
    a("// EP6 image windows recorded in this session (byte counts only).")
    a("struct ImageWindow { int chunks; long long bytes; double t_first;")
    a("                     double t_last; };")
    a("inline constexpr int kChunkBytes = %d;  // every recorded transfer" %
      (chunk_sizes.pop() if len(chunk_sizes) == 1 else 0))
    for i, w in enumerate(wins, 1):
        a("inline constexpr ImageWindow kWindow%d{%d, %d, %.3f, %.3f};"
          % (i, len(w), sum(n for _, n in w),
             w[0][0] - t0, w[-1][0] - t0))
    a("")
    a("} // namespace pakon::test::scan_fixture")
    a("")

    with open(out, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s: %d exchanges, %d windows" % (out, len(exchanges), len(wins)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
